### ISSUE TITLE
Switch to ZURB Foundation

### ISSUE THREAD

**Issue by MarauderXtreme** [fsr/ese-webseite#1]
First things first.
If we want to make this website mobile ready it would be wise to use a good framework.
I only know 2. Bootstrap and Foundation.
@JustusAdam and me are quite familiar with Foundation so smart choice!
I would suggest using [ZURB Foundation](http://foundation.zurb.com/) for the new site.

**Comment by JustusAdam** [comment]
Done as of commit e9fde80fb11abf21ad258b4a184be0e15ad83435
