### ISSUE TITLE
iCalender File missing

### ISSUE THREAD

**Issue by jgonsior** [fsr/ese-webseite#12]
Are you going to create an iCalender file for the timetable this year? If not, it would probably be a better idea to just remove the download link 
https://fsr.github.io/ese-webseite/ESE.ics

**Comment by MarauderXtreme** [comment]
I am not quite sure who generated it last time. Maybe this person will do it again this your. Otherwise you are right.

**Comment by kiliankoe** [comment]
I created last year's. I'll go ahead and do the same tomorrow or so for this year.

**Comment by JustusAdam** [comment]
The timetable is stored in a yaml data file. Can we generate the ical file from that automatically?

**Comment by kiliankoe** [comment]
Nice idea! Will do so.

**Comment by kiliankoe** [comment]
Added the updated ical file. It's a bit *tricky* to generate this from the yaml file and it might be the best idea to go from it the other way around in the future, so I still made this by hand. Not knowing where to put it I just threw it right into the root, please move it to wherever it should be going if not there.

**Comment by MarauderXtreme** [comment]
I will have a look on it.

**Comment by JustusAdam** [comment]
I looked at the ics file and made an new one that gets generated from the events.yaml file.
