### ISSUE TITLE
Update Timetable

### ISSUE THREAD

**Issue by jgonsior** [fsr/ese-webseite#13]
The timetable needs to be updated according to the one in the wiki.

**Comment by MarauderXtreme** [comment]
@JustusAdam or I will have a look later on it. If you want it to happen sooner you can do it by yourself. Just update this [yaml file](https://github.com/fsr/ese-webseite/blob/master/_data/events.yaml) with the correct data. Than it should get properly generated the next jekyll run.

**Comment by MarauderXtreme** [comment]
References f42480bdeeb973f5cc55570b682b437bc108e646

**Comment by MarauderXtreme** [comment]
Should be done with the last commit.
