### ISSUE TITLE
Bring the content

### ISSUE THREAD

**Issue by MarauderXtreme** [fsr/ese-webseite#16]
Someone should bring the content to the Website. This includes #5.    
We need to get this done.

**Comment by heisig** [comment]
Deutscher Content [hinzugefügt](https://github.com/fsr/ese-webseite/commit/c96874f413fed8a7521046eb0a4772e977dc522f)

Englischer folgt noch

**Comment by MarauderXtreme** [comment]
Can you merge them into gh-pages after you are finished? So that all can have a easy look on it.

**Comment by heisig** [comment]
Ich hab jetzt alles auf dem master soweit fertig. Bin mir nicht ganz sicher wie ich das dann auf die gh-pages bringe. Möchte nichts kaputt machen. Kann das vielleicht jemand kurz übernehmen?

**Comment by MarauderXtreme** [comment]
Well. It would have been much easier if you seperated those things in some more commits. I will have a look on this.

**Comment by heisig** [comment]
Ja das mag sein. Mein git-workflow ist noch nicht wirklich optimiert.

**Comment by MarauderXtreme** [comment]
Done with e713f3144b5ad99a4b5f377f2125d0926d960a58
