### ISSUE TITLE
Slider on no-js

### ISSUE THREAD

**Issue by MarauderXtreme** [fsr/ese-webseite#18]
Maybe there is a way to add the first slider with the src attribute. So that at least one picture gets displayed. I know that @JustusAdam has talked about stripping a first element from an array. Maybe he can have a look at this.

**Comment by JustusAdam** [comment]
Sure you can strip it, but I'm not sure how much the slider will like that. Consider a noscript instead.

**Comment by MarauderXtreme** [comment]
Maybe we just try it. This should not be done for a launch but rather as improvement for next years.
