### ISSUE TITLE
responsive design

### ISSUE THREAD

**Issue by frankhedecke** [fsr/ese-webseite#20]
This site does not look responsive to me.

![not responsive](https://cloud.githubusercontent.com/assets/7064194/9990720/c3cb0e58-6063-11e5-9902-ddae1888cd09.png)

**Comment by MarauderXtreme** [comment]
Which version do you use? I thought I had set the breakpoint correctly but maybe we have do to adjust this setting.

**Comment by MarauderXtreme** [comment]
The overflowing topbar should be fixed by now. the problem with the table is discussed in #15.

**Comment by frankhedecke** [comment]
Wenn http://fsr.github.io/ese-webseite/ die aktuelle Version ist, dann ist der Bug immernoch da.

**Comment by MarauderXtreme** [comment]
Nope. Not merged yet.
Can you provide me some information about when this bug happens. That I can investigate if the browsers behave differently.

**Comment by kiliankoe** [comment]
as far as I know Frank was using Firefox' debugging tools to simulate a mobile device for this to occur.

**Comment by MarauderXtreme** [comment]
Okay. I just tested it on my Firefox with mobile mode but it seems to work. Even on the current gh-page.
It correctly breaks on 725px. Even when the font-size of the browser is higher, it still works.
![725x480](https://cloud.githubusercontent.com/assets/6439489/9996915/c1bee212-6089-11e5-8b91-8aeb6b4ca1ee.png)

**Comment by MarauderXtreme** [comment]
Is there still this issue?

**Comment by MarauderXtreme** [comment]
I assume that this was fixed due to no update or further information.
