### ISSUE TITLE
Switching back to foundation styles

### ISSUE THREAD

**Issue by MarauderXtreme** [fsr/ese-webseite#21]
I've just discovered that @JustusAdam has made some huge changes to the standard layout of foundation within the _base.scss. Maybe this was to adapt the old layout but in my opinion this is not the right way. I always thought that something is not right with the scaling of the website but now I have found the error.
When I got time I will create a branch with a refactored SCSS and than we can discuss about it.

**Comment by MarauderXtreme** [comment]
Maybe this will fix the width problem that @sjmielke mentioned in #11. There are some CSS rules that make the content smaller than it could be and I try to adress this in this issue.

**Comment by sjmielke** [comment]
Some issues:
* `h3`s don't stand out enough, that makes reading the other pages a bit difficult. Perhaps some more whitespace? :P
* Very minor issue: some space between the accordion and the following paragraph would probably be nicer.
* IMO major issue: no option to view the time*table* from the mobile layout. I don't think this is okay....
* I really like the new menu color, but I'm not sure about the menu bar and the (nice new) language switcher. I think the language switcher should be a little bit less high, so both heights match and I also think that there should be a little bit vertical space between the image slider and the menubar - just like it is on the right. But I don't know if especially the first thing maybe looks very different on your machines, for me it's slightly better in Chromium...
* The slider takes ages to load properly... is that just me or is something seriously wrong there?

**Comment by MarauderXtreme** [comment]
> IMO major issue: no option to view the timetable from the mobile layout. I don't think this is okay....

Won't fix. Works as designed. The timetable is too wide and will always overflow the viewport of a handheld device. That is the problem with the table.

> The slider takes ages to load properly... is that just me or is something seriously wrong there?

There is an option to lazy load image in slick slider. We used this because it reduced HTTP roundtrips on initial page load. If correct caching and compression settings are made on the fsr servers this should not lag anymore.

**Comment by dirkonet** [comment]
> Won't fix. Works as designed. The timetable is too wide and will always overflow the viewport of a handheld device. That is the problem with the table.

Sorry, but if it's intended to designed people who only just arrived in Dresden and only have a mobile device to check the timetable, then the design is wrong. Please make the timetable available somehow, don't care about looks.

**Comment by JustusAdam** [comment]
Didn't we agree already to just show the non-table version? @dirkonet nobody wants to exclude mobile users from the schedule itself just the table layout. The events would still be listed with all the information.

**Comment by sjmielke** [comment]
An event list is no replacement for a timetable. If including it in the website threatens the serene harmony of your responsive piece of art, at least include a nice big link to a plain old no-bullshit-HTML file that contains just this table.

**Comment by MarauderXtreme** [comment]
A mobile ready design was a requirement. We discussed this topic a long time ago with @heisig and he agreed that it is better to bring a list to mobile devices rather than having a layout breaking ugly-ass thingy on the phone. (I think that even his initial plan was something like this even before jekyll, foundation or whatever)
Don't you understand that one does not want to scroll through this table on a small device. A list is a better way to view this information on a mobile device.
What you call bullshit HTML is the only proper way.
We are the web developer in charge. You can report what you thinks works not correctly and discuss about it but you must accept when we say that this is not possible.
We are trying to think like the end user and not a dev and that's where this decission originates.

I will lock this issue until the version that was the original topic of this issue is in place.

**Comment by MarauderXtreme** [comment]
With 859ce643fe80bf17508552640c9425ec021b1fc3 I created the refactored version of this site. I think many of the problems reported should now be fixed or at least in a state where they do not bother much.
I too have reduced the CSS. Now the theme only uses Foundation styles and custom non-modular styles. With this I introduced a draft for easy color switching. You can find the variables under css/style.scss. Than it only needs new content and an adapted logo every year.

Known/Obvious Bugs:
* Slider Picture are too small and create a white padding
* related to the slider the logo scales differently and the language switcher will be not on the same height

Please feel free to discuss and provide feedback for this version.

@sjmielke Nope. I will not implement a plain HTML version of the timetable. ^^

**Comment by JustusAdam** [comment]
I found another bug. There's some sort of small white padding next to the timetable on the right. Perhaps some excess td's. I may have to have a look into that.

**Comment by MarauderXtreme** [comment]
Right. I noticed them too but have forgotten to write them down.

**Comment by MarauderXtreme** [comment]
On request I merged the refactoring into gh-pages that no one has to install jekyll to compile and have a look at it.
Done with cf47ae1f739b0ac7a2e86f80f2678de68693841a

**Comment by MarauderXtreme** [comment]
Merged with 1eb4ff5c3559a5cc5bbffa22cbe08cc07d776d12

Now only this weird little table bug and the small pictures in the slider persist.
