### ISSUE TITLE
Launch

### ISSUE THREAD

**Issue by MarauderXtreme** [fsr/ese-webseite#23]
Could you please update/close as soon as this version is online.

**Comment by MarauderXtreme** [comment]
Hey Hey Hey. Very nice.
:beer: @JustusAdam 
:beer: @heisig

**Comment by kiliankoe** [comment]
:notes: Hey, hey, hey, ich bin der ... :notes: 

![](http://www.marktplatz-osnabrueck.de/portaldata/1/Resources/iload/550937137392BSC_big.jpg)

**Comment by MarauderXtreme** [comment]
Wrong side of the river. He resides on the dark side. We don't talk about this part of out beautiful city.
