### ISSUE TITLE
ESE Kino

### ISSUE THREAD

**Issue by frankhedecke** [fsr/ese-webseite#27]
Unter Wo, soll das Kino im Kasten noch hin.

Könnt ihr irgendwo notieren, dass das Kino 2 Euro Eintritt kostet und 3 Euro für mitgebrachte Gäste.

**Comment by heisig** [comment]
Kino wurde im Commit 1848ed88f5bf0e9bab9249b1411ea7f9274a17b5 eingefügt. Preise trage ich nach.
