### ISSUE TITLE
RFC Documentation review

### ISSUE THREAD

**Issue by JustusAdam** [fsr/ese-webseite#3]
I've written some [basic docs](/fsr/ese-webseite/wiki) about site structure. Please review. 

I'd like to get feedback on what else would have to be explained in order for everyone else to be able to also edit the page, based on that documentation.

**Comment by JustusAdam** [comment]
Oh yes, mentions! Who do I want in on this?
Well, definitely @heisig, @LarsEngeln and @MarauderXtreme. Who else? Well I think the website team @sjmielke should have a look at it and perhaps @kiliankoe who also usually has some useful insight. 

Anyone else potentially involved?

**Comment by MarauderXtreme** [comment]
Looks quite okay. But you need to add documentation for multilanguage after you've written it.

**Comment by JustusAdam** [comment]
I am moving to an on-demand model for expanding the documentation.
