### ISSUE TITLE
Unable to create a file in the directory! Please check your server settings.

### ISSUE THREAD

**Issue by MaxMatti** [fsr/ese-webseite#32]
[https://ese.ifsr.de/2014/fotos.html](https://ese.ifsr.de/2014/fotos.html)

Warning: fopen(/srv/web/ese.ifsr.de/htdocs/2014/wp-content/database/.htaccess): failed to open stream: Permission denied in /srv/web/ese.ifsr.de/htdocs/2014/wp-content/plugins/sqlite-integration/pdoengine.class.php on line 282
Unable to create a file in the directory! Please check your server settings.
Fatal error: Call to a member function prepare() on null in /srv/web/ese.ifsr.de/htdocs/2014/wp-content/plugins/sqlite-integration/pdoengine.class.php on line 615

Wollte mir die Bilder der letzten ESE angucken. Wenn das ein 404 sein soll, sollte der anders aussehen.

Edit: [https://ese.ifsr.de/2014](https://ese.ifsr.de/2014)* sind alle betroffen

**Comment by kiliankoe** [comment]
@sebschrader wird das wieder fixen ;) Thx

**Comment by MarauderXtreme** [comment]
Has this been fixed? Is so, please close it! @sebschrader

**Comment by sebschrader** [comment]
Keine PHP-Fehler mehr und Server sendet 404 Code, aber ein ordentliche Fehlermeldung kommt trotzdem nicht.

Werde Marcus das Wordpress zu exportieren.
