### ISSUE TITLE
The Table

### ISSUE THREAD

**Issue by JustusAdam** [fsr/ese-webseite#33]
...

Edit: Still need to fix the weird issue in refactoring.

**Comment by MarauderXtreme** [comment]
Oh. Our beloved topic is back again?

**Comment by JustusAdam** [comment]
Yes :smile:

**Comment by JustusAdam** [comment]
So what you're saying is there's no way to do this basically?

**Comment by MarauderXtreme** [comment]
There is now way to do it like @sjmielke wants it **and** have a responsive design.
