### ISSUE TITLE
Version for 2016

### ISSUE THREAD

**Issue by JustusAdam** [fsr/ese-webseite#34]
Revised version for the new years ESE.

TODO:

- [ ] Change color (yellow)
- [x] The Table #33 
- [x] Finish layout
- [ ] Amend content for new year
    - [ ] Update dates
    - [ ] Check links

**Comment by dirkonet** [comment]
Please also have at least a preliminary version with the most important dates online in July/early August as that's when the first information leaflets are sent out.

**Comment by MarauderXtreme** [comment]
Well I think it would be first necessary to merge the updated version. So that we have clean CSS.

**Comment by MarauderXtreme** [comment]
I link the open issues here.
- [ ]   #18
- [ ]   #19
- [ ]   #21
- [ ]   #24 
- [ ]   #26
