### ISSUE TITLE
gh-pages branch

### ISSUE THREAD

**Issue by kiliankoe** [fsr/ese-webseite#4]
Would it be possible to also deploy the site to a gh-pages branch in this repo for quick previewing of the current state (not as the official version, that's still on ese.ifsr.de)? 
That'd be cool :)

**Comment by dirkonet** [comment]
Only with additional no-index etc. parameters for search engines – otherwise, freshers might find github first.

**Comment by kiliankoe** [comment]
sounds reasonable

**Comment by JustusAdam** [comment]
Wasn't this rejected a while back?

**Comment by MarauderXtreme** [comment]
I too think this was rejected for some reasons. Reasons no one knows. ^^
I'm fine with it. If someone with authority can click the button in settings, we can merge mobile to it.

**Comment by kiliankoe** [comment]
what button?

I still agree with Dirk though that we'd need to be clear on the page itself (by preventing search engine indexing and maybe a note as well) that this is not the official page.

**Comment by JustusAdam** [comment]
Like a big red banner DEVELOPER PREVIEW - AUTHORISED PERSONNEL ONLY

**Comment by MarauderXtreme** [comment]
The Banner and the robots.txt is no problem but I have no access to the settings where the creation of the gh-pages branch is done. (That's why someone with authority should do it.)

In my opinion the robots.txt is enough even if the bots are not required to follow the rules. As far as I know the most important crawler follow the rules. So it should be enough for this short time period.

**Comment by kiliankoe** [comment]
You don't need the repo settings to create a gh-pages branch. As long as it's called `gh-pages` github will pick up on it and publish the branch contents under `username.github.io/reponame`.

A robots.txt is probably fine, you're right. A banner with a link to ese.ifsr.de sounds good as well :)

**Comment by MarauderXtreme** [comment]
Okay. I wasn't aware of that. Could someone check my dev version in the new branch and rename the branch if it is satisfying.

**Comment by MarauderXtreme** [comment]
LOOKATIT:
https://fsr.github.io/ese-webseite/
