### ISSUE TITLE
Multi language support.

### ISSUE THREAD

**Issue by JustusAdam** [fsr/ese-webseite#5]
As of commit c740780c46d95f2954d7aa2594fcf95ddaae6caf the site supports translation into english.

All necessary infrastructure is in place.

The following directories mirror the german content:

- _en_posts ↔︎ _posts
- _en_sidebar ↔︎ _sidebar
- _en_news ↔︎ _news
- _en ↔︎ all pages at the root (/) (like "faq" and "fotos")

Now someone has to take it upon themselves to translate those content pages into english.

**Comment by MarauderXtreme** [comment]
I think is is a good job for @heisig, isn't it?

**Comment by MarauderXtreme** [comment]
Should be done with c6fabdc3da16b91d5ca259f60f2a8c9f39b2e73d
