### ISSUE TITLE
Fixing Timetable Layout

### ISSUE THREAD

**Issue by MarauderXtreme** [fsr/ese-webseite#7]
As you can see we have rewritten the code of the timetable so that it gets generated and is a proper table. But now is the problem that it overflows the grid because it doesn't give a shit about anything. (btw. tables HTML are horrible and bad and one day I will suffer severe brain damage from thinking how to style a table correctly)

For now we need to search for the cause that makes the table overflow and fix it for medium up. I will look through this but if you see a cause try a fix.

My proposal for small devices would be to just hide the table and show the list-like barrier free version of this table. This has to be coded. @JustusAdam Maybe it is the best if you do this.

**Comment by MarauderXtreme** [comment]
Maybe someone with a better understanding or a better look for too long words can check my hyphenation in the events.yaml. I know this last overflow can be fixed but I don't see the overflow monster.

**Comment by MarauderXtreme** [comment]
Okay. Maybe someone can check my hyphenation. I think I have a bit over-hyphenated.

**Comment by JustusAdam** [comment]
There is no need to hardcode the shortdate in 3afdfbc5c75b42704b728fdd12cd6cc2f6649aba  

Liquid provides [filters](https://docs.shopify.com/themes/liquid-documentation/filters/additional-filters) for rendering dates in various ways. You can use those tho render one single date in two different ways.

**Comment by MarauderXtreme** [comment]
Okay. Could you possibly implement this. I don't see through the documentation.

**Comment by MarauderXtreme** [comment]
480ef95bb2e4239cb52b742071a37573e98e814e belongs to this issue.

**Comment by MarauderXtreme** [comment]
Thank you @JustusAdam for correcting this.
