### ISSUE TITLE
Language Switcher

### ISSUE THREAD

**Issue by MarauderXtreme** [fsr/ese-webseite#8]
I will try to code some JS magic, that generates links for switching languages. Maybe there is a way to do it while compile time but for now I will do my best with JS.

**Comment by JustusAdam** [comment]
That is not necessary. We can generate those in liquid.

**Comment by JustusAdam** [comment]
I added url generation in commit e253b5e2d2f48d3f55d44e26b433740ee0ed82ab

**Comment by MarauderXtreme** [comment]
Well. I have to reopen this issue because this new switcher somehow doesn't work with my changes so easily.

**Comment by JustusAdam** [comment]
No, this issue is closed. You changed the language switcher in the gh-pages branch, but thats not where your changes should go.

You'll have to properly cherry pick your changes into master.

**Comment by MarauderXtreme** [comment]
I need this issue open until I merged it properly.

**Comment by MarauderXtreme** [comment]
@JustusAdam was so kind and picked the commits into the master. It should be done by now.
